usertoken: xoxp-708948424145-708948424305-744813614020-3b3d478fa7a3edaa7567c2a86ec06782
bottoken: xoxb-708948424145-745505481845-PbGbfb5dzj88slW4EPzjuhre
elasticurl: https://vpc-elasti-test-4xae3alsxtpwfn66t53d46mk64.us-west-2.es.amazonaws.com
reports:
  - name: daily-standup
    channel: '#daily-standup'
    users:
      - name: sebastian
      - name: berto
    schedule:
      period: weekly
      mon: true
      tues: true
      wed: true
      thurs: true
      fri: true
      sat: false
      sun: false
      time: '09:00'
      timeZone: user-local
      excludeHolidays: US
    intromessage: hello {{.Name}}! It's time for our daily standup meeting.
    questions:
      - text: What did you do yesterday?
        color: '#2196F3'
      - text: What will you do today?
        color: '#4CAF50'
      - text: Anything blocking you progress?
        color: '#FFEB3B'
      - text: Anything else to add?
        color: '#673AB7'
